env:
  browser: true
  es6: true
  node: true
extends:
  - 'plugin:react/recommended'
  - standard
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - prettier
rules:
  prettier/prettier:
    - error
    - arrowParens: "avoid"
      endOfLine: "auto"
      # 120 is max, but 80 is preferred
      printWidth: 120
      semi: false
      singleQuote: true
      trailingComma: "none"
